### ISSUE TITLE
Milliseconds

### ISSUE THREAD

**Issue by mmxw11** [palechip/HudPixel#102]
I think you should add milliseconds back to tkr timer, because its time based game and its worked there good.

**Comment by palechip** [comment]
The problem is that the timer has to synchronize with the official lap times. And as they don't provide milliseconds, the mod has no way of knowing the exact time. This means any milliseconds the timer shows are only fake accuracy.

I'd rather have no milliseconds than some inaccurate ones.

However if you see a way of getting accurate values, I would immediately re-add them.
